{% set version = "None" %}
{% set name = "m4ri" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/malb/m4ri/downloads/{{ name }}-{{ version }}.tar.gz
  sha256: 217650584e39cc986812aa6c5ea1631226a93941eece11b769b1aa661b6eda26

build:
  number: 0

requirements:
  build:
    - libtool  # [not win]
    - {{ compiler('c') }}
  host:
    - libpng
    - zlib
  run:
    - libpng
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/m4ri/m4ri.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://bitbucket.org/malb/m4ri
  license: GPLv2+
  license_file: {{ SRC_DIR }}/COPYING
  summary: M4RI is a library for fast arithmetic with dense matrices over F2
  dev_url: https://bitbucket.org/malb/m4ri
  doc_url: https://malb.bitbucket.io/m4ri

extra:
  recipe-maintainers:
    - isuruf
