travis:
  secure:
    BINSTAR_TOKEN: STJs2Q8skUaJE9/I5ZhuXgIP6C+0Jn+ekZ14RJ9hvdcDBVZ6xr5dn6bcdX9/hJNWLsO3jnOpfyk/7KRbrJeu2/vZAfmhWNnd+nkLCi9lmeNkACWpiUC0fJ9ZiJr+YgnK/FracWYlFi8cHig0ujd8e5Za0r8XXmQkC89c09g3ynT7aQp2OyQLmu+IyxRGG8gWzdEu3X0mANflAuiTUYIdXProz5KEjEf0fdy1gOqz4GDINnKbzBz9C+wdy6bPfnyCjjckV2C3kGCTyb+kjQRQ7ATebu7gvFgoex/4WcYPdoCYkmVp4ZvSG/f+qmllGfawL6llLQ8LAIajKpJZBBgYqWG+/kYIPaz85ns1LCSRnVW5LkerMjreHBRt3XV1eYZGELTzwGZXJODM38Wj4CDnpe9fD9+QqBJk95VbaRo0Wxp7V7KAx44CR/GxfH4nvQ7IClOGgOF71jUtIdWOrNkUQjfBY5hbKhcDawUt8tTgEL0ldjqAs4qt/CXhaDkLt7wwCV2yx4wW4yM45AIMb6pcqB80D4zPVOg1z8H8uhMnN0aIfhgnMQcnq1QDdPHQNbI4HbMSqUU2+7sEIuyQqD6H68xLdQzpE4sCq33SRwMcUZaOyjishABV0qoFmYpdbE9ioiRYfRFKP+BftOjmPbtBiobK5Miw6k3BNft0oG6WH1c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
