travis:
  secure:
    BINSTAR_TOKEN: IAMbKghjFpwPD9Gl80AqtPF4xCAM+hJg4fxWUVRj3ZH33J4TWpVn8Xb8NvAc5DvyCLdDb+nSSkuNI/sEsbBqmDd2PdAKUbNiW4f7Mx0VEgZPF6yRV0vCisMeQfVLztfXQx73+z0Su1QBT7EiYVdeOJITyO8k3MH3yXehqFxirZd4C5zvrRvd0hGZDorYyWr6bKSwg00/pQ3RKF8FhAr1ePmug+xxWWyjCXLNaMqlH0YvZH38J1wJE4j2ZPGV6f0NX5NddTHHTckgMZi0zLkZCqbOY3gVv4BS96T1QWbao2B89AjKYMfONVcosWkklFF4qUaS3pl9b4nLcsjVVomPHW/+ZLkbCU+II7N2a5fevpqhPxLFTQHimFel3Z3io67RZIno3JCBVBi1Bv45CE5M0DV7WKUkQ8vFJkFdaIh/gCP6CSzMPgxUgWoR1Df4elLtDcPgUP8iGS/j1z5Z7xs+SyUqc7EwcOGVsUBxdHkTZd2I5TJ49aBtYvM1qGcatnMMOwEa1RcA7M6T6LY+SYvrYYtza6nf/iTMXHR4tpND/YxScqo0/9jJYjuNC44aTmG3D1vYynFClNFIFnVuXCWh59t/uA0uBFnaCbS/db9yNIDXQdZGoMTP92Ak+e2v4KAgmZ84SklEXBQzGHPqBbag5tnTGyiBb0aRhd/K1Vfu46w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
